window.ANSWER_BOOK_CARDS = [
  {
    cardImage: "./cards/cardimage-1.png",
    cardName: "【SSR】 - 九小孩",
    songCover: "./cards/songcover-1.jpg",
    lyric: "我不再问错与对，生出翅膀就高飞",
    songInfo: "《九小孩》 张韶涵",
  },
  {
    cardImage: "./cards/cardimage-2.png",
    cardName: "【SSR】 - 宇宙超级无敌大",
    songCover: "./cards/songcover-2.jpg",
    lyric: "宇宙超级无敌大",
    songInfo: "《宇宙超级无敌大》 王源",
  },
  {
    cardImage: "./cards/cardimage-3.png",
    cardName: "【SSR】 - 冬泳",
    songCover: "./cards/songcover-3.jpg",
    lyric: "我拼命呼吸，生与死，我都会游到底",
    songInfo: "《冬泳》 李宇春",
  },
  {
    cardImage: "./cards/cardimage-4.png",
    cardName: "【SSR】 - 冬泳",
    songCover: "./cards/songcover-4.jpg",
    lyric: "我最后悔的决定，是跃入那条河",
    songInfo: "《冬泳》 李宇春",
  },
  {
    cardImage: "./cards/cardimage-5.png",
    cardName: "【SSR】 - 永远都记得",
    songCover: "./cards/songcover-5.jpg",
    lyric: "永远都记得最初的自己，相信去爱只需要有勇气",
    songInfo: "《永远都记得》 单依纯",
  },
  {
    cardImage: "./cards/cardimage-6.png",
    cardName: "【SSR】 - 日落",
    songCover: "./cards/songcover-6.jpg",
    lyric: "尽管被放取代，不表示光不存在，你的爱让我明白，视线之外无形同载",
    songInfo: "《日落》 孙燕姿",
  },
  {
    cardImage: "./cards/cardimage-7.png",
    cardName: "【SSR】 - 可惜没如果",
    songCover: "./cards/songcover-7.jpg",
    lyric: "那么多如果，可能如果我，可惜没如果，只剩下结果",
    songInfo: "《可惜没如果》 林俊杰",
  },
  {
    cardImage: "./cards/cardimage-8.png",
    cardName: "【SSR】 - 一念光",
    songCover: "./cards/songcover-8.jpg",
    lyric: "那火种微弱却还跳动着，去凝望闪着光",
    songInfo: "《一念光》 张韶涵",
  },
  {
    cardImage: "./cards/cardimage-9.png",
    cardName: "【SSR】 - 雨天",
    songCover: "./cards/songcover-9.jpg",
    lyric: "折纸飞机碰到雨天，终究会坠落",
    songInfo: "《雨天》 林俊杰",
  },
  {
    cardImage: "./cards/cardimage-10.png",
    cardName: "【SSR】 - 年少有为",
    songCover: "./cards/songcover-10.jpg",
    lyric: "假如我年少有为不自卑，懂得什么是珍贵",
    songInfo: "《年少有为》 李荣浩",
  },
  {
    cardImage: "./cards/cardimage-11.png",
    cardName: "【SSR】 - 泡沫",
    songCover: "./cards/songcover-11.jpg",
    lyric: "美丽的泡沫，虽然一刹花火",
    songInfo: "《泡沫》 G.E.M.邓紫棋",
  },
  {
    cardImage: "./cards/cardimage-14.png",
    cardName: "【SSR】 - 修炼爱情",
    songCover: "./cards/songcover-14.jpg",
    lyric: "笑着说爱让人疯狂，哭着说爱让人紧张，忘不了那个人就投降",
    songInfo: "《修炼爱情》 林俊杰",
  },
  {
    cardImage: "./cards/cardimage-16.png",
    cardName: "【SSR】 - 愿与愁",
    songCover: "./cards/songcover-16.jpg",
    lyric: "恋从挥手到牵手，到放手到挥手，就该足够",
    songInfo: "《愿与愁》 林俊杰",
  },
  {
    cardImage: "./cards/cardimage-17.png",
    cardName: "【SSR】 - 再见",
    songCover: "./cards/songcover-17.jpg",
    lyric: "不要对我说再见，一句再见，就结束这一切",
    songInfo: "《再见》 G.E.M.邓紫棋",
  },
  {
    cardImage: "./cards/cardimage-18.png",
    cardName: "【SSR】 - 等你下课",
    songCover: "./cards/songcover-18.jpg",
    lyric: "总有一天，总有一年会发现，有人默默地陪在你的身边",
    songInfo: "《等你下课》 周杰伦",
  },
  {
    cardImage: "./cards/cardimage-19.png",
    cardName: "【SSR】 - 珠玉",
    songCover: "./cards/songcover-19.jpg",
    lyric: "谁去明天遇见我啊，别让今天叫住我了",
    songInfo: "《珠玉》 单依纯",
  },
  {
    cardImage: "./cards/cardimage-20.png",
    cardName: "【SSR】 - Dear Life",
    songCover: "./cards/songcover-20.jpg",
    lyric: "就让我们一呼一吸，好好感受一分一秒活着",
    songInfo: "《Dear Life》 郁可唯",
  },
  {
    cardImage: "./cards/cardimage-21.png",
    cardName: "【SSR】 - Lovesick Girls",
    songCover: "./cards/songcover-21.jpg",
    lyric: "Didn't wanna be a princess, I'm priceless",
    songInfo: "《Lovesick Girls》 BLACKPINK",
  },
  {
    cardImage: "./cards/cardimage-22.png",
    cardName: "【SSR】 - SOLO",
    songCover: "./cards/songcover-22.jpg",
    lyric: "Used to be your girl, now I'm used to being the GOAT",
    songInfo: "《SOLO》 JENNIE",
  },
  {
    cardImage: "./cards/cardimage-23.png",
    cardName: "【SSR】 - Hammer",
    songCover: "./cards/songcover-23.jpg",
    lyric: "I'm ready to feel like I don't have the answers, there's peace in the madness over our heads",
    songInfo: "《Hammer》 Lorde",
  },
  {
    cardImage: "./cards/cardimage-24.png",
    cardName: "【SSR】 - 911",
    songCover: "./cards/songcover-24.jpg",
    lyric: "My biggest enemy is me",
    songInfo: "《911》 Lady Gaga",
  },
  {
    cardImage: "./cards/cardimage-25.png",
    cardName: "【SSR】 - idontwannabeyouanymore",
    songCover: "./cards/songcover-25.jpg",
    lyric: "Hands getting cold, losing feeling's getting old, was I made from a broken mold",
    songInfo: "《idontwannabeyouanymore》 Billie Eilish",
  },
  {
    cardImage: "./cards/cardimage-26.png",
    cardName: "【SSR】 - God is a woman",
    songCover: "./cards/songcover-26.jpg",
    lyric: "I can be all the things you told me not to be",
    songInfo: "《God is a woman》 Ariana Grande",
  },
  {
    cardImage: "./cards/cardimage-27.png",
    cardName: "【SSR】 - Born This Way",
    songCover: "./cards/songcover-27.jpg",
    lyric: "I'm beautiful in my way, 'cause God makes no mistake",
    songInfo: "《Born This Way》 Lady Gaga",
  },
];
